export default {
    MAX_USERS: 100,
    MAX_POSTS_PER_USER: 1000,

    MAX_USERNAME_LENGTH: 16,
    MAX_AVATAR_FILESIZE_BYTES: 1048576,
    MAX_BIO_LENGTH: 1680,
    MAX_SHORT_BIO_LENGTH: 140,
    MAX_POST_PREVIEW_LENGTH: 420,
    MAX_POST_LENGTH: 1680,
    MAX_DM_LENGTH: 500,

    NUMBER_OF_RETRIEVABLE_DM_S: 500,
    
    CLOUD_STORAGE_AVATAR_BUCKETNAME: "twitterclone-avatars",
    
    HANDLE_BATCH_SIZE: 5,
    NOTIFICATION_EXPIRY_DAYS: 30,
    FEED_ACTIVITY_EXPIRY_DAYS: 30,
    DAYS_OF_ACTIVITY_FOR_PUBLIC_FEED: 7,

    DELETED_DM_PLACEHOLDER: "[Deleted message]",
}