export default {
    MAX_USERNAME_LENGTH: 16,
    MAX_AVATAR_FILESIZE_BYTES: 1048576,
    MAX_BIO_LENGTH: 4200,
    MAX_SHORT_BIO_LENGTH: 140,

    CLOUD_STORAGE_AVATAR_BUCKETNAME: "twitterclone-avatars",
}